### ISSUE TITLE
Android mobile version 1.1.7 error

### ISSUE THREAD

**Issue by StormTurk** [aphtoken/aph-wallet-gui#175] opened 2018-09-05 23:18 UTC
The new wallet version has a bug . The wallet starts an RPC error if you add more than a single NEO address account during startup/opening the wallet. You won’t see the error with one wallet, but once you add 2 3 wallets you will see the RPC error in all of the wallets.

**Comment by apheliontoken** [comment] 2018-09-06 00:42
The problem is not related to having multiple wallet.s

**Comment by jsolman** [comment] 2018-09-16 22:54
We are tracking issues related to network timeouts separately outside of github for the mobile wallet. The issue doesn't seem to be related to the number of accounts in the wallet. Closing this since we are tracking it elsewhere.

**Closed by jsolman** 2018-09-16 22:54 UTC
